name: TruffleHog Scan

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  TRUFFLEHOG_VERSION: 3.90.6

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Install TruffleHog
        run: |
          curl -sL "https://github.com/trufflesecurity/trufflehog/releases/download/v${TRUFFLEHOG_VERSION}/trufflehog_${TRUFFLEHOG_VERSION}_linux_amd64.tar.gz" -o trufflehog.tar.gz
          tar -xzf trufflehog.tar.gz trufflehog
          chmod +x trufflehog
          sudo mv trufflehog /usr/local/bin/

      - name: Run TruffleHog
        id: scan
        env:
          EVENT_NAME: ${{ github.event_name }}
          BEFORE_SHA: ${{ github.event.before }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: |
          echo "Running TruffleHog v${TRUFFLEHOG_VERSION}..."

          if [ "${EVENT_NAME}" = "pull_request" ] && [ -n "${BASE_SHA}" ]; then
            SINCE_COMMIT="${BASE_SHA}"
          elif [ -n "${BEFORE_SHA}" ]; then
            SINCE_COMMIT="${BEFORE_SHA}"
          else
            SINCE_COMMIT="$(git rev-list --max-parents=0 HEAD)"
          fi

          echo "Scanning changes since ${SINCE_COMMIT}"

          trufflehog git "file://${GITHUB_WORKSPACE}" \
            --no-update \
            --since-commit "${SINCE_COMMIT}" \
            > trufflehog-report.txt

          STATUS=$?

          if [ "${STATUS}" -ne 0 ] && [ "${STATUS}" -ne 183 ]; then
            echo "TruffleHog failed with exit code ${STATUS}."
            cat trufflehog-report.txt
            exit "${STATUS}"
          fi

          if [ -s trufflehog-report.txt ]; then
            COUNT=$(grep -Ec '^✅ Found verified result|^Found unverified result' trufflehog-report.txt || true)
          else
            COUNT=0
          fi

          echo "Secrets found: ${COUNT}"
          echo "found=${COUNT}" >> "$GITHUB_ENV"
          echo "count=${COUNT}" >> "$GITHUB_OUTPUT"

      - name: Upload TruffleHog report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-report
          path: trufflehog-report.txt

      - name: Comment on PR if secrets found
        if: env.found != '0' && github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COUNT="${found}"
          REPO="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          RUN_URL="https://github.com/${REPO}/actions/runs/${{ github.run_id }}"
          MSG="🚨 *TruffleHog detected ${COUNT} potential secrets* in this PR. [View full report](${RUN_URL})"

          gh pr comment "${PR_NUMBER}" --repo "${REPO}" --body "${MSG}"

      - name: Fail if secrets found
        if: env.found != '0'
        run: |
          echo "❌ Secrets detected."
          exit 1
